const fs=require('fs');const path=require('path');require('dotenv').config({path:path.resolve(__dirname,'../../../.env')});const {connectDatabase}=require('../config/database');const {env}=require('../config/env');const {User,Board,Job,Community,Resource,Notification,FAQ,RecruitmentSource,NotificationPreference}=require('../models');const {slugify}=require('../services/source.service');const {prepareBootstrapConfig,reconcileBootstrapAccounts}=require('./bootstrapAccounts');
const seedPath=path.resolve(__dirname,'../../../data.json');
function parseDeadline(value){const parsed=new Date(value);if(!Number.isNaN(parsed.getTime()))return parsed;const match=String(value).match(/^(\d{1,2})(?:st|nd|rd|th)?\s+([a-z]+)\s+(\d{4})$/i);if(!match)return undefined;const month=new Date(`${match[2]} 1, 2000`).getMonth();if(Number.isNaN(month))return undefined;return new Date(Date.UTC(Number(match[3]),month,Number(match[1]),23,59,59,999));}
async function seed(){const bootstrapAccounts=prepareBootstrapConfig(process.env,env.nodeEnv);await connectDatabase(env.mongoUri);await reconcileBootstrapAccounts(bootstrapAccounts,User,NotificationPreference);const data=JSON.parse(fs.readFileSync(seedPath,'utf8'));const boardRows=[...data.boards,{name:'West Bengal Police',category:'police',icon:'building'}];const boards=new Map();for(const source of boardRows){const slug=slugify(source.name);const board=await Board.findOneAndUpdate({slug},{$set:{name:source.name,shortDescription:source.shortDescription||'',description:source.description||'',organization:source.organization||'',category:source.category||'',officialWebsite:source.url||'',officialNotificationWebsite:source.officialNotificationWebsite||'',location:source.location||'',icon:source.icon||''},$setOnInsert:{slug,active:source.active===true}},{upsert:true,new:true,setDefaultsOnInsert:true});boards.set(slug,board);}
const sources=new Map();for(const source of [{name:'UPSC',url:'https://www.upsc.gov.in/',official:true},{name:'SSC',url:'https://ssc.gov.in/',official:true},{name:'RRB',url:'https://www.rrbcdg.gov.in/',official:true},{name:'West Bengal Police',url:'https://wbpolice.gov.in/',official:true},{name:'WBCS'},{name:'BPSC'},{name:'CIL'}]){const item=await RecruitmentSource.findOneAndUpdate({name:source.name},{$setOnInsert:{name:source.name,organization:source.name,board:boards.get(slugify(source.name))?._id,websiteUrl:source.url,isOfficial:Boolean(source.official),sourceType:'MANUAL',active:false,fetchInterval:24,parserType:'not-configured'}},{upsert:true,new:true,setDefaultsOnInsert:true});sources.set(source.name,item);}
for(const item of data.jobs){const boardName=item.category==='police'?'West Bengal Police':item.organization;const board=boards.get(slugify(boardName))||boards.get('ssc');const recruitmentSource=sources.get(item.source);const deadline=parseDeadline(item.deadline);const slug=slugify(item.id);const existing=await Job.findOne({slug}).select('_id slug source sourceExternalId');const externalMatch=recruitmentSource?await Job.findOne({source:recruitmentSource._id,sourceExternalId:item.id}).select('_id slug'):null;if((existing&&(String(existing.source)!==String(recruitmentSource?._id)||existing.sourceExternalId!==item.id))||(externalMatch&&externalMatch.slug!==slug))continue;await Job.findOneAndUpdate({slug},{$set:{title:item.title,organization:item.organization,board:board?._id,boardName:board?.name,category:item.category,tags:item.tags,qualification:item.qualification,ageMin:Number((item.age||'').split(/[–-]/)[0])||undefined,ageMax:Number((item.age||'').split(/[–-]/)[1])||undefined,location:item.location,applicationDeadline:deadline,officialWebsite:item.officialUrl,source:recruitmentSource?._id,sourceUrl:item.officialUrl,sourceExternalId:item.id},$setOnInsert:{slug,description:`Seed/demo listing for ${item.title}. Verify the current official recruitment notification before applying.`,status:'PENDING_REVIEW',verificationStatus:'PENDING'}},{upsert:true,new:true,setDefaultsOnInsert:true});}
for(const item of data.communities){const board=boards.get(slugify(item.name.split(' ')[0]));await Community.findOneAndUpdate({slug:item.id},{$set:{name:item.name,description:item.description,board:board?._id,exam:item.name.replace(' Preparation',''),active:true},$setOnInsert:{slug:item.id}},{upsert:true,new:true,setDefaultsOnInsert:true});}
for(const item of data.preparation){await Resource.findOneAndUpdate({title:item.name,type:item.id==='papers'?'PYQ':item.id==='mock'?'MOCK_TEST':item.id==='syllabus'?'SYLLABUS':'STUDY_MATERIAL'},{$set:{description:item.description,active:true},$setOnInsert:{title:item.name,type:item.id==='papers'?'PYQ':item.id==='mock'?'MOCK_TEST':item.id==='syllabus'?'SYLLABUS':'STUDY_MATERIAL'}},{upsert:true,new:true,setDefaultsOnInsert:true});}
for(const item of data.notifications){const job=await Job.findOne({slug:slugify(item.jobId)});if(!job)continue;await Notification.findOneAndUpdate({user:null,title:item.text},{$setOnInsert:{type:'RECRUITMENT_UPDATE',title:item.text,message:item.text,relatedJob:job._id,published:false,user:null}},{upsert:true,new:true,setDefaultsOnInsert:true});}
for(let i=0;i<data.faqs.length;i++){const item=data.faqs[i];await FAQ.findOneAndUpdate({question:item.question},{$set:{answer:item.answer,order:i,active:true},$setOnInsert:{question:item.question}},{upsert:true,new:true,setDefaultsOnInsert:true});}
console.info('Seed completed idempotently. Demo job listings are pending human review and are not publicly searchable until approved and published.');await require('mongoose').disconnect();}
seed().catch(error=>{console.error({event:'seed_failure',errorType:error.name||'Error',code:error.code});process.exit(1);});
