const ROLES = Object.freeze({ USER: 'USER', AUTHOR: 'AUTHOR', ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' });
const JOB_STATUSES = Object.freeze(['DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', 'EXPIRED', 'ARCHIVED']);
const APPLICATION_STATUSES = Object.freeze(['NOT_APPLIED', 'APPLIED', 'ADMIT_CARD', 'EXAM_SCHEDULED', 'EXAM_COMPLETED', 'RESULT', 'INTERVIEW', 'SELECTED', 'REJECTED']);
module.exports = { ROLES, JOB_STATUSES, APPLICATION_STATUSES };
